// student authentication types
export const BUSINESS_LOGIN_REQUESTED = "BUSINESS_LOGIN_REQUESTED";
export const BUSINESS_LOGIN_SUCCESS = "BUSINESS_LOGIN_SUCCESS";
export const BUSINESS_LOGIN_FAILED = "BUSINESS_LOGIN_FAILED";
export const BUSINESS_LOGOUT = "BUSINESS_LOGOUT";
export const BUSINESS_REGISTER_REQUESTED = "BUSINESS_REGISTER_REQUESTED";
export const BUSINESS_REGISTER_SUCCESS = "BUSINESS_REGISTER_SUCCESS";
export const BUSINESS_REGISTER_FAILED = "BUSINESS_REGISTER_FAILED";

// admin authentication types
export const INVESTOR_LOGIN_REQUESTED = "INVESTOR_LOGIN_REQUESTED";
export const INVESTOR_LOGIN_SUCCESS = "INVESTOR_LOGIN_SUCCESS";
export const INVESTOR_LOGIN_FAILED = "INVESTOR_LOGIN_FAILED";
export const INVESTOR_LOGOUT = "INVESTOR_LOGOUT";
export const INVESTOR_REGISTER_REQUESTED = "INVESTOR_REGISTER_REQUESTED";
export const INVESTOR_REGISTER_SUCCESS = "INVESTOR_REGISTER_SUCCESS";
export const INVESTOR_REGISTER_FAILED = "INVESTOR_REGISTER_FAILED";

// BUSINESS PROFILE types
export const EDIT_PROFILE_REQUESTED = "EDIT_PROFILE_REQUESTED";
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAILED = "EDIT_PROFILE_FAILED";

export const GET_PROFILE_REQUESTED = "GET_PROFILE_REQUESTED";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILED = "GET_PROFILE_FAILED";
